apiVersion: v1
kind: Service
metadata:
  name: simplest-query-lb
  labels:
    app: simplest-query
spec:
  type: LoadBalancer 
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 16686
  selector:
    app: simplest-query
    